// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto.Models;

namespace Proyecto.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20190607195916_RolesCreate")]
    partial class RolesCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Proyecto.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(180);

                    b.Property<DateTime>("EndDate");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("ProjectID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Proyecto.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RolDsc")
                        .IsRequired();

                    b.Property<int>("RolLvlId");

                    b.HasKey("RoleId");

                    b.HasIndex("RolLvlId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Proyecto.Models.RoleLevel", b =>
                {
                    b.Property<int>("RolLvlId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RolLvlDsc")
                        .IsRequired();

                    b.HasKey("RolLvlId");

                    b.ToTable("RoleLevel");
                });

            modelBuilder.Entity("Proyecto.Models.Role", b =>
                {
                    b.HasOne("Proyecto.Models.RoleLevel", "level")
                        .WithMany()
                        .HasForeignKey("RolLvlId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
