// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Models;

namespace Proyecto.Migrations
{
    [DbContext(typeof(TechnicianRoleContext))]
    partial class TechnicianRoleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Project.Models.TechnicianRole", b =>
                {
                    b.Property<int>("TecRolId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TecRolDsc");

                    b.Property<string>("TecRolLvl");

                    b.HasKey("TecRolId");

                    b.ToTable("TechnicianRole");
                });
#pragma warning restore 612, 618
        }
    }
}
